version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_ngnix.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_ngnix.sh
      timeout: 300
      runas: root
